version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: sh entrypoint-dev.sh

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4001"
      - "4002:4002"
    volumes:
      - ./web:/app
    depends_on:
      - app
    command: yarn dev

  db:
    image: postgres:11.5
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
