app = "my-personal-space"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

# TODO figure out how to apply migrations with sqlite
# Manual steps in mean time:
#   1. fly ssh console
#   2. bin/my_personal_space remote
#   3. MyPersonalSpace.Release.migrate()
# [deploy]
#   release_command = "bin/my_personal_space eval \"MyPersonalSpace.Release.migrate()\""

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source="sqlite_data"
  destination="/app/db"

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
